# EDA ( Exploratory Data Analysis )
# Numpy

* ## Install Numpy

In [1]:
pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 4.2 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/12.6 MB 2.2 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.6 MB 2.5 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.6 MB 2.6 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.6 MB 2.6 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/12.6 MB 2.5 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.6 MB 2.5 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.6 MB 2.5 MB/s eta 0:00:04
   --------------- ------------------------ 4.7/12.6 MB 2.5 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.6 MB 2.6 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.6 MB 2.7 MB/s eta 0:00:03
   -------------------- ------------------- 6.6/12.6 MB 2.7 MB/s eta 0:00:03
   --

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


* ## Creating Arrays

In [2]:
import numpy as np

* ### np.array()

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Array created using np.array():", arr1)

Array created using np.array(): [1 2 3 4 5]


* ### np.zeros()
np.zeros() is a NumPy function used to create an array filled with zeros. The function takes the desired shape of the array as input and returns an array of that shape filled with zeros.

In [5]:
zeros_array = np.zeros((3, 4))

print("Array filled with zeros:")
print(zeros_array)

Array filled with zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


* ### np.ones()
np.ones() is a NumPy function used to create an array filled with ones.

In [6]:
ones_array = np.ones((3, 2))

print("Array filled with ones:")
print(ones_array)

Array filled with ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


* ### np.arange(start, stop, step)
Create an array with a range of values.



In [9]:
arr_custom = np.arange(5, 20, 3)

print("Custom array using np.arange(5, 21, 3):")
print(arr_custom)

Custom array using np.arange(5, 21, 3):
[ 5  8 11 14 17]


* ### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
Create an array of evenly spaced values over a specified interval.

In [11]:
arr = np.linspace(0, 1, num=11)

print("Array using np.linspace(0, 1, num=10):")
print(arr)

Array using np.linspace(0, 1, num=10):
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


* ## Array Operations
* np.sum(): Compute the sum of array elements.
* np.mean(): Compute the mean of array elements.
* np.max(): Find the maximum value in an array.
* np.min(): Find the minimum value in an array.
* np.std(): Compute the standard deviation of array elements.

In [12]:
arr1 = np.array([1, 2, 3, 4, 5])

In [13]:
total = np.sum(arr1)
print("Sum of array elements:", total)

Sum of array elements: 15


In [14]:
print("Mean of array elements:", np.mean(arr1))

Mean of array elements: 3.0


In [15]:
print("Max of array elements:", np.max(arr1))

Max of array elements: 5


In [16]:
print("Min of array elements:", np.min(arr1))

Min of array elements: 1


In [17]:
print("Standard Deviation of array elements:", np.std(arr1))

Standard Deviation of array elements: 1.4142135623730951


* ## Array Manipulation

* ### np.reshape()
Reshape an array.


In [18]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

In [21]:
# The product of 2 numbers should be equal to the array size, otherwise it will give error
reshaped_arr = np.reshape(arr1, (3, 2))
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


* ### np.transpose()
Transpose an array.

In [22]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [23]:
np.transpose(arr2)

array([[1, 4],
       [2, 5],
       [3, 6]])

* ### np.concatenate()
Concatenate arrays along a specified axis.

In [31]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

concatenated_arr = np.concatenate((arr1, arr2), axis=0)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated array along axis 0 (rows):")
print(concatenated_arr)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]]

Concatenated array along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]]


* ### np.split()
Split an array into multiple sub-arrays.

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# 2nd parameter should be factor of array size
sub_arrays = np.split(arr, 2)

In [36]:
sub_arrays

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

* ## Mathematical Functions
* np.sin(), np.cos(), np.tan(): Trigonometric functions.
* np.exp(): Exponential function.
* np.log(), np.log10(), np.log2(): Logarithmic functions.
* np.sqrt(): Square root function.
* np.absolute(): Absolute value function.

In [37]:
angles = np.array([0, np.pi/4, np.pi/2, np.pi])

In [38]:
sin_values = np.sin(angles)
cos_values = np.cos(angles)
tan_values = np.tan(angles)

print("Angles (in radians):", angles)
print("Sine values:", sin_values)
print("Cosine values:", cos_values)
print("Tangent values:", tan_values)

Angles (in radians): [0.         0.78539816 1.57079633 3.14159265]
Sine values: [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
Cosine values: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]
Tangent values: [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.22464680e-16]


* ### np.exp()

In [39]:
x = np.array([1, 2, 3, 4])

exp_values = np.exp(x)

print("Original array:", x)
print("Exponential values:", exp_values)

Original array: [1 2 3 4]
Exponential values: [ 2.71828183  7.3890561  20.08553692 54.59815003]


* ### np.log(), np.log10(), np.log2()

In [41]:
x = np.array([1, 10, 100])

log_values = np.log(x)
log10_values = np.log10(x)
log2_values = np.log2(x)

print("Original array:", x)
print("Natural logarithm (base e):", log_values)
print("Base-10 logarithm:", log10_values)
print("Base-2 logarithm:", log2_values)

Original array: [  1  10 100]
Natural logarithm (base e): [0.         2.30258509 4.60517019]
Base-10 logarithm: [0. 1. 2.]
Base-2 logarithm: [0.         3.32192809 6.64385619]


* ### np.sqrt()

In [42]:
x = np.array([4, 9, 16, 25])

sqrt_values = np.sqrt(x)

print("Original array:", x)
print("Square root values:", sqrt_values)

Original array: [ 4  9 16 25]
Square root values: [2. 3. 4. 5.]


* ### np.absolute()

In [43]:
x = np.array([-2, -1, 0, 1, 2])

absolute_values = np.absolute(x)

print("Original array:", x)
print("Absolute values:", absolute_values)

Original array: [-2 -1  0  1  2]
Absolute values: [2 1 0 1 2]
